Traceback (most recent call last):
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2851, in get_entry_map
    ep_map = self._ep_map
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2813, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map. Did you mean: '_dep_map'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dron/ws_controller/src/log_data_pkg/setup.py", line 5, in <module>
    setup(
  File "/home/dron/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/home/dron/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 142, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/home/dron/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 134, in __init__
    distutils.core.Distribution.__init__(self, filtered)
  File "/home/dron/.local/lib/python3.10/site-packages/setuptools/dist.py", line 451, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 641, in <genexpr>
    for entry in dist.get_entry_map(group).values()
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2853, in get_entry_map
    ep_map = self._ep_map = EntryPoint.parse_map(
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2534, in parse_map
    for group, lines in data:
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3190, in split_sections
    for line in yield_lines(s):
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2394, in yield_lines
    for ss in strs:
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2765, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1417, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1407, in get_metadata
    value = self._get(path)
  File "/home/dron/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1611, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dron/ws_controller/install/flask_pkg/lib/python3.10/site-packages/flask_pkg-0.0.0-py3.10.egg-info/entry_points.txt'
